image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
- hugo
environment:
  site: brbe.net
tasks:
- package: |
    cd $site
    hugo
    tar -cvz . > ../site.tar.gz
- upload: |
    hut pages publish -d $site site.tar.gz

